application:
  name: user
spring:
  profiles: lattice
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: hsqldb
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost:8083}
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: development
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: false
